# Generated by Django 3.2.9 on 2022-09-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_active',
            new_name='is_archive',
        ),
    ]
